// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
const REFRESH_WINDOW_SECONDS = 60;

/**
 * Server functions run as separate HTTP requests, so they need a current bearer
 * token on every call. `getSession()` can return the locally persisted token
 * just before the background refresher has replaced it; refresh it here when
 * it is near expiry instead of sending a token the API will reject.
 */
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    let {
      data: { session },
    } = await supabase.auth.getSession();

    const expiresSoon =
      !session?.expires_at ||
      session.expires_at <= Math.floor(Date.now() / 1000) + REFRESH_WINDOW_SECONDS;
    if (session && expiresSoon) {
      const refreshed = await supabase.auth.refreshSession();
      session = refreshed.data.session ?? null;
    }

    return next({
      headers: session?.access_token ? { Authorization: `Bearer ${session.access_token}` } : {},
    });
  },
);
